import { StyledComponentsRegistry } from '@/components';
import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const APP = {
  NAME: 'Next App Router Starter',
  DEFAULT_TITLE: 'Next App Router Starter',
  TITLE_TEMPLATE: '%s - Next App Router Starter',
  DESCRIPTION:
    'Generated by create next app [project-name] -e https://github.com/rahulrajdahal/next-starter',
};

export const metadata: Metadata = {
  applicationName: APP.NAME,
  title: {
    default: APP.DEFAULT_TITLE,
    template: APP.TITLE_TEMPLATE,
  },
  description: APP.DESCRIPTION,
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: APP.DEFAULT_TITLE,
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: 'website',
    siteName: APP.NAME,
    title: {
      default: APP.DEFAULT_TITLE,
      template: APP.TITLE_TEMPLATE,
    },
    description: APP.DESCRIPTION,
  },
  twitter: {
    card: 'summary',
    title: {
      default: APP.DEFAULT_TITLE,
      template: APP.TITLE_TEMPLATE,
    },
    description: APP.DESCRIPTION,
  },
};

export const viewport: Viewport = {
  themeColor: '#FFFFFF',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          {children}
          <Toaster />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
